# Generated by Django 2.0 on 2019-07-02 11:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('membership_no', models.CharField(max_length=10)),
                ('date_join', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name:')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname:')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name:')),
                ('photo', models.ImageField(blank=True, upload_to='members_photos')),
                ('sex', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], default='F', max_length=10)),
                ('id_no', models.CharField(blank=True, max_length=10, verbose_name='ID No')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='DATE OF BIRTH')),
                ('phone_no', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Phone number.')),
                ('phone_no2', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Alternate phone number.')),
                ('email', models.CharField(blank=True, max_length=40)),
                ('occupation', models.CharField(blank=True, max_length=35)),
                ('county', models.CharField(blank=True, max_length=35, verbose_name='PLACE OF BIRTH: County')),
                ('subcounty', models.CharField(blank=True, max_length=35, verbose_name='PLACE OF BIRTH: Sub County')),
                ('ward', models.CharField(blank=True, max_length=35, verbose_name='PLACE OF BIRTH: Ward')),
                ('village', models.CharField(blank=True, max_length=35, verbose_name='PLACE OF BIRTH: Village')),
                ('membership_no', models.CharField(max_length=35, unique=True, verbose_name='Membership No')),
                ('residence', models.CharField(blank=True, max_length=35, verbose_name='Current place of Residence.')),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('Bank', models.CharField(blank=True, max_length=30)),
                ('Branch', models.CharField(blank=True, max_length=30)),
                ('ac_no', models.CharField(blank=True, max_length=30)),
                ('nok_name', models.CharField(blank=True, max_length=30, verbose_name='NEXT OF KIN.  Name:')),
                ('nok_relationship', models.CharField(blank=True, max_length=30, verbose_name='NEXT OF KIN.  Relationship:')),
                ('nok_id', models.CharField(blank=True, max_length=30, verbose_name='NEXT OF KIN.  Id No /Birth Certificate:')),
                ('beneficiaries', models.TextField(blank=True, max_length=50)),
            ],
        ),
    ]
