# Generated by Django 2.0 on 2019-07-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone number.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_no2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Alternate phone number.'),
        ),
    ]
