# Generated by Django 2.0 on 2019-07-29 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0002_auto_20190702_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups_extra_details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chairman_name', models.CharField(max_length=50)),
                ('secretary_name', models.CharField(max_length=50)),
                ('treasurer_name', models.CharField(max_length=50)),
                ('chairman_id', models.IntegerField()),
                ('secretary_id', models.IntegerField()),
                ('treasurer_id', models.IntegerField()),
                ('postal_address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('county', models.CharField(blank=True, max_length=35, verbose_name='Physical Address: County')),
                ('subcounty', models.CharField(blank=True, max_length=35, verbose_name='Physical Address: Sub County')),
                ('ward', models.CharField(blank=True, max_length=35, verbose_name='Physical Address: Ward')),
                ('village', models.CharField(blank=True, max_length=35, verbose_name='Physical Address: Village')),
                ('Bank', models.CharField(blank=True, max_length=30)),
                ('ac_name', models.CharField(blank=True, max_length=30)),
                ('ac_no', models.CharField(blank=True, max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Groups')),
            ],
            options={
                'verbose_name': 'Group detail',
                'verbose_name_plural': 'Group       details',
            },
        ),
    ]
