# Generated by Django 2.0 on 2019-07-02 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges_refrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Particulars', models.CharField(choices=[('loan_form', 'Loan Form'), ('office', 'Office charges')], max_length=20)),
                ('Amount', models.IntegerField(blank=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Debts_register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('charge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Finance.Charges_refrence')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursed_Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date_disbursment', models.DateTimeField()),
                ('Amount', models.IntegerField()),
                ('date_last_principal', models.DateField()),
                ('Borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Member')),
                ('gurantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gurantor', to='Membership.Member')),
            ],
        ),
        migrations.CreateModel(
            name='fines_refrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offence', models.CharField(choices=[('non_contribution', 'Non-contribution'), ('principal_latness', 'Falirue to pay monthly loan principal')], max_length=10)),
                ('Amount', models.IntegerField(blank=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='gshare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('date_payment', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_repayment_refrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('repayment_period', models.IntegerField(verbose_name='Repayment Period in Months')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('date_payment', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Member')),
            ],
        ),
        migrations.AddField(
            model_name='debts_register',
            name='fine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Finance.fines_refrence'),
        ),
        migrations.AddField(
            model_name='debts_register',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Membership.Member'),
        ),
    ]
