# Generated by Django 2.0 on 2019-07-29 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_groups_extra_details'),
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDisbursed_Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date_disbursment', models.DateField()),
                ('Amount', models.IntegerField()),
                ('installments', models.IntegerField(blank=True, default=12, verbose_name='Repayment Period in Months')),
                ('date_last_principal', models.DateField(blank=True, editable=False)),
                ('re_paid', models.BooleanField(default=False)),
                ('Borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Groups')),
                ('gurantor', models.ManyToManyField(related_name='Gurantors_group_loan', to='Membership.Member')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDisbursed_Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date_disbursment', models.DateField()),
                ('Amount', models.IntegerField()),
                ('installments', models.IntegerField(blank=True, default=12, verbose_name='Repayment Period in Months')),
                ('re_paid', models.BooleanField(default=False)),
                ('Borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Member')),
                ('gurantor', models.ManyToManyField(blank=True, related_name='Gurantors_individual_loan', to='Membership.Member')),
            ],
        ),
        migrations.CreateModel(
            name='loan_repayment_register_group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('date_payment', models.DateField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.GroupDisbursed_Loan')),
            ],
        ),
        migrations.CreateModel(
            name='loan_repayment_register_individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('date_payment', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.IndividualDisbursed_Loan')),
            ],
        ),
        migrations.RemoveField(
            model_name='disbursed_loan',
            name='Borrower',
        ),
        migrations.RemoveField(
            model_name='disbursed_loan',
            name='gurantor',
        ),
        migrations.DeleteModel(
            name='Disbursed_Loan',
        ),
    ]
