# Generated by Django 2.0 on 2019-08-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_auto_20190729_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts_register',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='debts_register',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='debts_register',
            name='member',
        ),
        migrations.DeleteModel(
            name='Debts_register',
        ),
    ]
