# Generated by Django 2.2.9 on 2020-02-21 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_auto_20190813_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges_record_group',
            name='Particulars',
            field=models.CharField(choices=[('loan form', 'loan_form'), ('office', 'office_fee'), ('exitfee', 'exit_fee'), ('newMembership', 'new_membership')], max_length=30),
        ),
        migrations.AlterField(
            model_name='charges_record_group',
            name='group',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='Membership.Groups'),
        ),
        migrations.AlterField(
            model_name='charges_record_individual',
            name='Particulars',
            field=models.CharField(choices=[('loan form', 'loan_form'), ('office', 'office_fee'), ('exitfee', 'exit_fee'), ('newMembership', 'new_membership')], max_length=30),
        ),
        migrations.AlterField(
            model_name='charges_record_individual',
            name='member',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='Membership.Member'),
        ),
        migrations.AlterField(
            model_name='fines_payment_register_individual',
            name='fine',
            field=models.ManyToManyField(related_query_name='fines', to='Finance.fines_record_individual'),
        ),
        migrations.AlterField(
            model_name='fines_record_group',
            name='Particulars',
            field=models.CharField(choices=[('non contribution', 'non_contribution'), ('Loan Fine', 'loan_fine'), ('Interest Fine', 'interest_fine'), ('Absentism', 'absentism'), ('Cashfines', 'cash_fine'), ('lateReceipt', 'late_receipt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fines_record_group',
            name='group',
            field=models.ForeignKey(blank=True, default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='Membership.Groups'),
        ),
        migrations.AlterField(
            model_name='fines_record_individual',
            name='Particulars',
            field=models.CharField(choices=[('non contribution', 'non_contribution'), ('Loan Fine', 'loan_fine'), ('Interest Fine', 'interest_fine'), ('Absentism', 'absentism'), ('Cashfines', 'cash_fine'), ('lateReceipt', 'late_receipt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fines_record_individual',
            name='member',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='Membership.Member'),
        ),
    ]
