# Generated by Django 2.2.9 on 2020-02-21 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_groups_extra_details'),
        ('Finance', '0005_auto_20200221_0732'),
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_Capital_deductions_individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Member')),
            ],
            options={
                'verbose_name': 'Share Capital individual',
                'verbose_name_plural': 'Share Capital individuals',
            },
        ),
        migrations.CreateModel(
            name='Share_Capital_deductions_group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membership.Groups')),
            ],
            options={
                'verbose_name': 'Share Capital group',
                'verbose_name_plural': 'Share Capital groups',
            },
        ),
        migrations.CreateModel(
            name='Loanoffset_deductions_individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance_amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.IndividualDisbursed_Loan')),
            ],
            options={
                'verbose_name': 'Loan offset individual',
                'verbose_name_plural': 'Loan offset individuals',
            },
        ),
        migrations.CreateModel(
            name='Loanoffset_deductions_group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance_amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.GroupDisbursed_Loan')),
            ],
            options={
                'verbose_name': 'Loan offset group',
                'verbose_name_plural': 'Loan offset groups',
            },
        ),
    ]
