"""
Django settings for jiendeleze project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret
SECRET_KEY = 'q!8v3pu(&7%4m0altkv=!qhowoxrmi52ghbj4de4!ajzq&c^8g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['selfhelp.jiendeleze.cloudns.ph', '165.22.124.74']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Membership',
    'Finance',
    'Reports',
    'corsheaders',
    'rest_framework', 
    'django.contrib.humanize',
    'background_task',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jiendeleze.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/srv/sites/jshg_portal/static/temps/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jiendeleze.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'djongo',
        'NAME': 'jiendeleze_db',
        'USER': 'jshg_db',
        'PASSWORD':'The Inland Monggitto 11',
        'ENFORCE_SCHEMA': 'False',
        'AUTH_SOURCE': 'jiendeleze_db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATICFILES_FINDERS = [
'django.contrib.staticfiles.finders.FileSystemFinder',
'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

AWS_ACCESS_KEY_ID = '6Y4KV26P3PHJGSV5623A'
AWS_SECRET_ACCESS_KEY = 'X7AKJNH8kCxQRs8gvsIV9K1fM6JxoRmY0eiiaiOoY30'
AWS_STORAGE_BUCKET_NAME = 'church'
AWS_S3_ENDPOINT_URL = 'https://ams3.digitaloceanspaces.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'jiendeleze'

STATIC_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/srv/sites/jshg_portal/static',
    '/srv/sites/jshg_portal/media',
    '/srv/sites/jshg_portal/static/admin/'

]

MEDIA_ROOT= '/srv/sites/jshg_portal/media/profilepics'
MEDIA_URL= 'media/'


ADMIN_MEDIA_ROOT= 'srv/sites/jshg_portal/media/'
ADMIN_MEDIA_URL= '/media/'
DATE_INPUT_FORMATS = ['%m/%d/%Y']



# security settings 

SECURE_HSTS_SECONDS=0

SECURE_HSTS_INCLUDE_SUBDOMAINS=False

SECURE_HSTS_PRELOAD= False

SECURE_CONTENT_TYPE_NOSNIFF=True

SECURE_BROWSER_XSS_FILTER=True

SECURE_SSL_REDIRECT=False

CSRF_COOKIE_SECURE=True

SESSION_COOKIE_SECURE=True

X_FRAME_OPTIONS='DENY'

AWS_DEFAULT_ACL = None
# logging settings

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'WARNING': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log', 'warnings.log')
        },
         'CRITICAL': {
            'level': 'CRITICAL',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log', 'critical.log')
        },

         'ERROR': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log', 'dj_error.log')
        },

        'INFO': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log', 'info.log')
        },
    },
    'loggers': {
        'django': {
            'handlers': ['WARNING', 'CRITICAL', 'ERROR', 'INFO'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'devtrusoft@gmail.com'
EMAIL_HOST_PASSWORD = 'trusofttechrwfe'
